### ISSUE TITLE
Error Extending and Instantiating NexusInstance

### ISSUE THREAD

**Issue by Sequal32** [TheNexusAvenger/Nexus-Instance#1]
On the newest release, and using the code from the documentation under "Simplified Constructor", implementation errors are thrown.

```  
17:02:49.255 - Workspace.NexusObject.NexusObject:315: NexusConnection does not implement the following:
  17:02:49.255 - 	NexusEvent.Disconnected
  17:02:49.256 - 	NexusEvent.Connect
  17:02:49.256 - 	NexusEvent.Wait
  17:02:49.256 - 	NexusEvent.Disconnected
  17:02:49.256 - 	NexusEvent.Connect
  17:02:49.256 - 	NexusEvent.Wait
17:02:49.257 - Stack Begin
17:02:49.257 - Script 'Workspace.NexusObject.NexusObject', Line 315 - field new
17:02:49.257 - Script 'Workspace.NexusObject.Event.LuaEvent', Line 60 - method Connect
17:02:49.258 - Script 'Workspace.NexusObject.Script', Line 15 - method __new
17:02:49.258 - Script 'Workspace.NexusObject.NexusObject', Line 296 - field new
17:02:49.259 - Script 'Workspace.NexusObject.Script', Line 29
17:02:49.259 - Stack End
```
Running tests for NexusInstance throws similar errors.

**Comment by TheNexusAvenger** [comment]
I did fix it but the fix isn't live yet since the old project exporter I had was deleted and the successor (Nexus Git) is incomplete. The next version also has a ~60% memory improvement.
No ETA when this will uploaded, but it should be within the next month. I will leave the issue open until it is up.

**Comment by Sequal32** [comment]
Thanks for the quick response!

**Comment by TheNexusAvenger** [comment]
Nexus Git is getting really close to usable as an alpha release. I am hoping to have the fix up within the next 2 weeks.

**Comment by Sequal32** [comment]
Awesome! Looking forward to using it again in my projects!

**Comment by TheNexusAvenger** [comment]
Nexus Instance V1.2.0 has been released. I am able to pull the repository to my file system, pull it into Roblox Studio using Nexus Git (releasing soon), and run the tests (releasing at some point, but not that soon). Closing this issue since it is resolved.
https://github.com/TheNexusAvenger/Nexus-Instance/releases/tag/V1.2.0
